apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-management
  template:
    metadata:
      labels:
        app: account-management
    spec:
      containers:
        - name: account-management
          image: shivammittal242/account-management-service:tag
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB_NAME
              value: devops
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 10
